name: Hourly Curl + Commit NEW3

on:
  schedule:
    - cron: "1 * * * *"   # every hour at minute 1 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Generate dated file
        run: |
          NOW=$(date -u +%Y-%m-%d-%H)

          YEAR=${NOW:0:4}
          MONTH=${NOW:5:2}
          DAY=${NOW:8:2}
          HOUR=${NOW:11:2}

          DIR="$YEAR/$MONTH"
          FILE="$DIR/$DAY-$HOUR.json"

          mkdir -p "$DIR"

          curl -k -L https://code.golf/scores/all-holes/all-langs/all > "$FILE"

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Update $(date -u +%Y-%m-%d-%H)" || exit 0

          git push